### ISSUE TITLE
Difference to the built-in?

### ISSUE THREAD

**Issue by MisterOBrien** [tylerhall/import-pinboard-archive-to-devonthink#1]
Heya,

Just curious if you tried the built-in Pinboard import script and what you found lacking? 

Just needed my user/pass for the initial prompt then it downloaded a bunch of .webloc files pretty seamlessly. After that it's just a matter of selecting which (or all) of the sites you want to archive, then right-click > Convert > To Web Archive.

**Comment by tylerhall** [comment]
Hey, there.

The built-in importer is a good solution, however it will only archive your bookmarks as they currently are _today_. Using the script I wrote with your Pinboard archive will store them as they were when you _originally_ bookmarked them. It will also let you archive websites which have gone offline or changed significantly since you first added them to Pinboard.

**Comment by MisterOBrien** [comment]
That makes a lot of sense, I hadn't thought of that. 

Only fairly recently did I upgrade to the Pinboard archiving plan, so I don't have archives that go back a long way. I can see the importance for someone who does.
